spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: cargo9088@gmail.com
    password: wkutveorncbagzjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
  logging:
    level:
      root: info
      am.itspace: debug
    file:
      name: "#{systemProperties['user.home']}/cargo/log/"
    logback:
      rollingpolicy:
        max-file-size: 1MB
  liquibase:
    change-log: classpath:liquibase/db/change-log.xml
    enabled: true

  mvc:
    validation:
      enabled: true
api:
  url: https://countriesnow.space/api/v0.1/countries/population/cities
