spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: cargo9088@gmail.com
    password: wkutveorncbagzjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          debug: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      root: info
      am.itspace: debug
    file:
      name: "#{systemProperties['user.home']}/cargo/log/"
    logback:
      rollingpolicy:
        max-file-size: 1MB
  liquibase:
    change-log: classpath:liquibase/db/change-log.xml
    enabled: true

  mvc:
    validation:
      enabled: true


