spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:liquibase/db/change-log.xml
    enabled: true

api:
  url: https://countriesnow.space/api/v0.1/countries/population/cities
